### ISSUE TITLE
Error: Cannot find module 'request'

### ISSUE THREAD

**Issue by mica83** [JanHalozan/iTunesConnectAnalytics#50]
Hi people, i'm testing this module but i have some problems.

I created a new empty node project with a new file "index.js" with this boilerplate code:

```
var itc = require('itunesconnectanalytics');
var Itunes = itc.Itunes;
var AnalyticsQuery = itc.AnalyticsQuery;

var username = 'UNAME';
var password = 'PASS';
var appId = '12345'; //Found in My Apps -> App -> Apple ID or read below on getting the app id.

var instance = new Itunes(username, password, {
  errorCallback: function(e) {
    console.log('Error logging in: ' + e);
  },
  successCallback: function(d) {
    console.log('Logged in');
  }
});
```

**But when i run the command `node index.js` i get this error:**

```
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)

```

thanks

**Comment by peralmq** [comment]
As a workaround, you can do `npm install request`.

**Comment by mica83** [comment]
> As a workaround, you can do `npm install request`.

I tried, but also after this command the problem still.

Any suggestions?

**Comment by peralmq** [comment]
I got the same error message as you and got it working after a separate npm install of the request package. That's all I know unfortunately. Maybe we experienced different errors but got the same error message then?

**Comment by mica83** [comment]
I don't know, it's strange. How did you create empty node project? 
I did the following steps

1) install module `npm install itunesconnectanalytics`
2) create empty node project with the command `npm init`
3) create a new file (index.js) in the project with the "usual boilerplate" code as indicated in project home
4) install dependency `npm install request`
5) run the code `node index.js`

But i have the errore indicated in the previous post 




> I got the same error message as you and got it working after a separate npm install of the request package. That's all I know unfortunately. Maybe we experienced different errors but got the same error message then?
> […](#)
> On 11 Dec 2020, 10:47 +0100, Michele Cavalcanti ***@***.***>, wrote: > As a workaround, you can do npm install request. I tried, but also after this command the problem still. Any suggestions? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by peralmq** [comment]
Same but 1. and 2. was swapped. Do you see the request folder under node_modules/? I.e. is the request package really there?

**Comment by mica83** [comment]
Yeah! with point 1 and point 2 swapped it work! Thanks man

**Comment by peralmq** [comment]
Woho! 😁
